#!/usr/bin/env perl
# progress - summarize line-based stdout to one dynamic progress line
use feature qw(unicode_strings);
use open qw(:std :utf8);
use warnings;
use strict;
use Text::CharWidth qw(mbwidth mbswidth);

$| = 1;

my ($width, $count, $last);

$width = int(`stty size </dev/tty | awk '{print \$2}'`);
$count = 0;
$last = time;

$SIG{INT} = sub {
	printf("\r\033[K%s\n", "$count items (interrupted)");
	exit 1;
};

while (++$count, my $str = <STDIN>) {
	my ($now, $out, $len, $chr);

	$now = time;
	#next if $now - $last < 1;
	$last = $now;

	chomp($str);
	$out = sprintf("%d ", $count);
	$len = length($out);
	if ($len + mbswidth($str) > $width) {
		while ($str ne "" && $len < $width) {
			$chr = substr($str, 0, 1, "");
			$len += mbwidth($chr);
			last if $len > $width;
			$out .= $chr;
		}
	} else {
		$out .= $str;
	}
	printf("\r\033[K%s\r", $out);
	sleep 1;
}

printf("\r\033[K%s\n", "$count items");
